# -*- coding: utf-8 -*-
"""Pr 8 - K Means Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl3McSCMTBd3eLuNdYF59uQwNLvgMDDO
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Load the data from the CSV file
df = pd.read_csv("age.csv")

# Extract features (Age and Time_Spent)
X = df[['Age', 'Time_Spent']]

# Define the number of clusters
k = 3

# Create KMeans instance
kmeans = KMeans(n_clusters=k)

# Fit KMeans to the data
kmeans.fit(X)

# Get cluster centers and labels
centers = kmeans.cluster_centers_
labels = kmeans.labels_

# Plot the data points and cluster centers
plt.scatter(df['Age'], df['Time_Spent'], c=labels, cmap='viridis', alpha=0.5)
plt.scatter(centers[:, 0], centers[:, 1], c='red', marker='X',
            label='Cluster Centers')
plt.xlabel('Age')
plt.ylabel('Time Spent on Gadgets')
plt.title('K-means Clustering')
plt.legend()
plt.show()

age_unknown = [[55, 0]]  # Here, 0 is a placeholder for the time spent (since we want to predict it)

# Use the trained KMeans model to predict the cluster for the given age
cluster_1 = kmeans.predict(age_unknown)

# Get the cluster center for the predicted cluster
cluster_center_1 = centers[cluster_1]

# Print the predicted cluster and the corresponding cluster center (estimated time spent on gadgets)
print("Predicted cluster for the given age", cluster_1)
print("Estimated time spent on gadgets for the given age", cluster_center_1[:,1][0])

