# -*- coding: utf-8 -*-
"""Practical 4 - Hypothesis Testing (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bZonpcJVEkGMD6ei9tkUxcFCXT4K3wN
"""

import pandas as pd
from scipy import stats

# Load the CSV file into a DataFrame
df = pd.read_csv("D:\\DS\\grades.csv")
print(df)
# Perform paired t-test
t_statistic, p_value = stats.ttest_rel(df['Before'], df['After'])

# Print the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Interpret the results
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The course has a significant effect
    on the grades.")
else:
    print("Fail to reject the null hypothesis: The course does not have
    a significant effect on the grades.")

import numpy as np
from scipy.stats import ttest_1samp
# Sample data: Delivery times (in minutes)
delivery_times = [28, 32, 30, 35, 29, 27, 31, 34, 33, 29]
# Hypothesized population mean
hypothesized_mean = 30
# Perform one-sample t-test
t_stat, p_value = ttest_1samp(delivery_times, hypothesized_mean)
# Print results
print("T-statistic:", t_stat)
print("P-value:", p_value)
# Significance level
alpha = 0.05
# Interpret results
print("\nHypotheses:")
print("Null Hypothesis (H0): The mean delivery time is 30 minutes.")
print("Alternate Hypothesis (H1): The mean delivery time is not 30 minutes.")

if p_value < alpha:
    print(f"\nResult: Reject the null hypothesis (p = {p_value:.4f} < {alpha}).")
    print("Conclusion: The mean delivery time is significantly different from 30 minutes.")
else:
    print(f"\nResult: Fail to reject the null hypothesis (p = {p_value:.4f} ≥ {alpha}).")
    print("Conclusion: There is no significant evidence that the mean delivery time differs from 30 minutes.")

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Construct a decision tree model
model = DecisionTreeClassifier()
model.fit(X, y)

# Visualize the decision tree
plt.figure(figsize=(12, 8))

plot_tree(model, feature_names=iris.feature_names, class_names=iris.target_names, filled=True)
plt.show()

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# Load the Breast Cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42)

# Construct a decision tree model
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train, y_train)

# Visualize the decision tree
plt.figure(figsize=(12, 8))
plot_tree(model, feature_names=data.feature_names, class_names=data.target_names, filled=True)
plt.show()

import numpy as np
import scipy.stats as stats

# Create a dummy dataset of 10 year old children's weight
data = np.random.randint(20, 40, 10)

# Define the null hypothesis
H0 = "The average weight of 10 year old children is 32kg."

# Define the alternative hypothesis
H1 = "The average weight of 10 year old children is more than 32kg."

# Calculate the test statistic
t_stat, p_value = stats.ttest_1samp(data, 32)

# Print the results
print("Test statistic:", t_stat)
print("p-value:", p_value)

# Conclusion
if p_value < 0.05:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

