# -*- coding: utf-8 -*-
"""Practical 3 - Feature Scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOqPc-zT3mfHfJb5EWH0AkcZUAhARHVL
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
# %matplotlib inline

data=pd.read_csv('Data_for_Missing_Values.csv')
data.head(15)

data=data.dropna()
data

#calculationg mean,median before feature scaling
#data.mean()
data.select_dtypes(include=['number']).mean()

data.median()

#slicing the feature age and salary
df=data.iloc[:,1:3].values
df



#MinMaxScaler or Normalization
min_max_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
df_after_minmax=min_max_scaler.fit_transform(df)
df_after_minmax

#Standarization
ss=preprocessing.StandardScaler()
df_after_ss=ss.fit_transform(df)
df_after_ss

#calculating mean,median after feature scaling
df_after_minmax.mean()

